"""empty message

Revision ID: 257629320a26
Revises: e9fcc0d11346
Create Date: 2021-03-14 21:56:03.613576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257629320a26'
down_revision = 'e9fcc0d11346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'tan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('tan', sa.VARCHAR(length=333), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
