"""empty message

Revision ID: 32a7a730ab03
Revises: 
Create Date: 2021-03-14 23:59:31.541636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a7a730ab03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('tan', sa.String(length=333), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'tan')
    # ### end Alembic commands ###
