"""empty message

Revision ID: aa9b9cc536c6
Revises: 32a7a730ab03
Create Date: 2021-03-15 00:00:05.785720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9b9cc536c6'
down_revision = '32a7a730ab03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'tan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('tan', sa.VARCHAR(length=333), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
