"""empty message

Revision ID: db7a57e4f1ec
Revises: 5c2944b7db80
Create Date: 2021-03-15 00:05:12.897831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7a57e4f1ec'
down_revision = '5c2944b7db80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'tryna')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('tryna', sa.VARCHAR(length=77), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
