"""empty message

Revision ID: e9fcc0d11346
Revises: 
Create Date: 2021-03-14 21:55:05.402301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9fcc0d11346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('tan', sa.String(length=333), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'tan')
    # ### end Alembic commands ###
